// Mapeamento de Veículo -> Motorista
export const DRIVER_MAP = {
  '26': 'LINDOMAR PEREIRA GOMES',
  '27': 'CLAUDINIR JOSE MACHADO',
  '28': 'FRANCIS HIME VALADARES SANTOS',
  '29': 'LUCIO CLAUDIO MONTEIRO DE ARAUJO',
  '30': 'CARLOS JAIR MARQUES',
  '31': 'ERASMO LIMA DA SILVA',
  '32': 'DENIS ROSATO FRANCO',
  '33': 'ADAUTO BENEDITO DA LUZ',
  '34': 'MARCIO PEREIRA DA SILVA',
  '35': 'GENILSO ROBERTO FRANCO',
  '36': 'JEFFYTER DO NASCIMENTO GONCALVES',
  '37': 'HELIO TAVARES DA SILVA',
  '38': 'JOSE LUCIANO DE OLIVEIRA GOMES',
  '39': 'MARCOS RODRIGUES LEMOS',
  '40': 'FABIANO TEIXEIRA ALVIM',
  '41': 'ALEXANDRO MORAIS PINHEIRO',
  '42': 'UANDERSON PEREIRA DA COSTA',
  '43': 'CLAUDIO DENES MARQUES',
  '44': 'PAULO MARINHO GAMA',
  '45': 'MARCIO BENTO DA SILVA',
  '46': 'CARLOS ANDRE DE FREITAS',
  '47': 'ROMARIO BORGES RODRIGUES',
  '48': 'ALEXANDRE DE LIMA',
  '49': 'ROBERTO SERGIO DOS SANTOS',
  '50': 'JULIO CESAR VICTORIO',
  '101': 'ANDRE DA SILVA DOS SANTOS',
  '102': 'RONEI PEREIRA DA SILVEIRA',
  '103': 'APARICIO CAVALCANTE NETO',
  '104': 'DARLEI RODRIGUES PEREIRA',
  '105': 'IRIS REZENDE DE OLIVEIRA DA SILVA',
  '106': 'ANTONIO OLIVEIRA',
  '107': 'CLODOALDO BUCHMEIER',
  '108': 'VANDO DE OLIVEIRA SENA',
  '109': 'ANTONIO ROGERIO GOMES RIBEIRO',
  '110': 'JOAO DA LUZ SILVA JUNIOR',
  '111': 'ANDRE LUIZ OLIVEIRA',
  '112': 'ALEXANDRE CUSTODIO DE OLIVEIRA',
  '113': 'GISELE DA CRUZ CHAVES',
  '114': 'ALFEU RAFAEL FILHO',
  '115': 'GILCIMAR SILVA BARROS',
  '116': 'JOSE PETRONIO DA SILVA',
  '117': 'JOSE ADOLFO DE ARAUJO',
  '118': 'ROCIELLE BARBOSA DA COSTA CARDOZO',
  '119': 'RANGEL CARDOZO ALVES',
  '120': 'VALTENILSON RIBEIRO BATISTA',
  '121': 'ANTONIO DE AVILA LIMA JUNIOR',
  '122': 'MAYCON JONI SOUZA REZENDE',
  '123': 'FRANCISCO SILVANO VIEIRA DE SOUZA',
  '124': 'DANIEL CAMARGO FERREIRA',
  '125': 'JOELSON ARAUJO DE AQUINO',
  '126': 'NILTON CESAR DOS SANTOS',
  '127': 'FABIO ALVES DE OLIVEIRA',
  '128': 'EDER WILSON DA SILVA',
  '129': 'JOSE ILSON DOS SANTOS MILIANO',
  '130': 'CARLOS ANTONIO REZENDE DE MORAES',
  '131': 'BALTAZAR LIMA DA CRUZ',
  '132': 'VITOR ROBERTO DINIZ FILHO',
  '133': 'NILVAN SEBASTIAO DO PRADO',
  '134': 'CLAITON MARTINS DA CUNHA',
  '135': 'REGINALDO DA CONCEICAO RIBEIRO',
  '136': 'GERALDO GONCALVES DA SILVA',
  '137': 'WESLEY RODRIGUES GONCALVES',
  '138': 'RUBINALDO SILVA REIS',
  '139': 'RAIMUNDO GUIMARAES DA SILVA',
  '140': 'SHERNNERY POULMMIER ALVES DE SOUZA',
  '141': 'OLAVO FERNANDES FILHO',
  '142': 'RAIMUNDO MOTA SANTANA JUNIOR',
  '143': 'CLEBER ALVES PEREIRA',
  '144': 'REGINALDO GERVASIO FIGUEIRA',
  '145': 'RUBENS BERNARDES',
  '146': 'DANIEL OLIVEIRA DE CASTRO',
  '147': 'CELIO PEREIRA DA FONSECA',
  '148': 'ELOIR DE SENE BECKER',
  '149': 'ALCIMAR CARLOS DA COSTA FARIAS',
  '150': 'RENATO MEDINA DE AZEVEDO',
  '204': 'AGNALDO SILVA OLIVEIRA',
  '205': 'DANIEL CASTRO RAMOS',
  '206': 'REINALDO JOSE GONCALVES',
  '207': 'EDUARDO RODRIGUES RIBEIRO',
  '208': 'JONAS DA COSTA RAMOS',
  '209': 'PATRICIA CRISTINA ARAUJO FERREIRA',
  '210': 'MARCOS PEREIRA LIMA',
  '211': 'ANTONIO MARCOS PINHEIRO SILVA',
  '212': 'CESAR AUGUSTO BARBOSA DA SILVA',
  '213': 'DENILSON JIENBA',
  '214': 'ELOISIO DIAS DA SILVA',
  '215': 'JHONATA CARDOSO AIRES',
  '216': 'RAIMUNDO VALERIO FIGUEIRA',
  '217': 'DAMIAO APARECIDO DA SILVA',
  '218': 'MANOEL PEREIRA BATISTA',
  '219': 'WENDERSON SOARES RIBEIRO',
  '220': 'CARLOS AVENTINO REIS DE OLIVEIRA',
  '221': 'ADAILVO TELES DOS SANTOS',
  '222': 'ANTONIO CARLOS SILVA SOUZA',
  '223': 'MARCOS AURELIO ROMUALDO',
  '224': 'VALBER SOUZA DOS SANTOS',
  '225': 'LUIS FLAVIO MEIRIM BRITO',
  '226': 'CLAUDIO JOSE DE SOUZA',
  '227': 'VANDERLAN COSTA OLIVEIRA',
  '228': 'DARCI DONIZETE FREITAS GONCALVES',
  '229': 'ADEZUISON DA SILVA SANTOS',
  '230': 'CARLOS ALBERTO DA SILVA',
  '231': 'EDVALDO DONIZETI DAMASIO',
  '232': 'LUIZ CARLOS FERREIRA',
  '233': 'WILMAR LUIZ DOS SANTOS',
  '234': 'WESLEY DOS SANTOS PAULA',
  '235': 'JOSE ANTONIO DE SOUSA',
  '236': 'CANDIDO DE SOUSA E SILVA',
  '237': 'JOAO BATISTA DA SILVA',
  '238': 'AILTON DA ROCHA MOREIRA',
  '239': 'REGINALDO DE LIMA SILVA',
  '240': 'UENDEL WILLIAN DE SOUZA',
  '241': 'UENES APARECIDO SANTOS',
  '242': 'FRANCISCO DAS CHAGAS SENA CARVALHO',
  '243': 'ANTONIO SOBRINHO RODRIGUES DOS SANTOS',
  '244': 'FERNANDO EMIDIO DOS SANTOS',
  '245': 'JOSE CARLOS SANTOS DA SILVA',
  '246': 'NILTON PAULO RODRIGUES SILVA',
  '247': 'NILTON HIGINO DOS SANTOS',
  '248': 'GABRIEL DA SILVA CARVALHO',
  '249': 'JOAO BATISTA DA SILVA',
  '250': 'CLEIDIMAR SILVA DE ALCANTARA',
  '251': 'ANDERSON SILVA CORREIA',
  '252': 'RAIMUNDO NONATO DE SOUSA SANTOS',
  '253': 'CHARLLEM DE FREITAS GUIMARAES',
  '254': 'LUIS CARLOS SILVA FRANCA',
  '255': 'UENDER DE ANDRADE VIEIRA',
  '304': 'SILVANIO ALVES DE OLIVEIRA',
  '305': 'ROGERIO LIMA',
  '306': 'FRANCISCO WAGNON SANTOS CRUZ',
  '307': 'FABIO SOARES PEREIRA',
  '308': 'REGIO FERNANDO CHAVES PERES',
  '309': 'EDVAR RODRIGUES MONTALVAO',
  '310': 'JOSE APARECIDO HENRIQUE FELIPE',
  '311': 'GERSON MOREIRA COSTA JUNIOR',
  '312': 'ROGERIO PEREIRA DA SILVA',
  '313': 'JULIO CESAR FERREIRA ALEXANDRE',
  '314': 'JONAS COSTA DAMASCENO',
  '315': 'JOSE CLEVER ALVES DE ANDRADE',
  '316': 'JULIANO RODRIGO SANTOS',
  '317': 'JOSE ANTONIO DOS SANTOS',
  '318': 'EDSON NUNES DE SOUZA',
  '319': 'ELDER VIDAL DOS SANTOS SILVA',
  '320': 'DARIO LEITE DE OLIVEIRA',
  '321': 'VALDEIR DA SILVA ALMEIDA',
  '322': 'RAILSON PEREIRA',
  '323': 'CARLOS JOSE DOS SANTOS',
  '324': 'ROGERIO SALES DOS SANTOS',
  '325': 'LUCIANO SILVA DOS SANTOS',
  '326': 'ANTONIO SEBASTIAO DA SILVA',
  '327': 'CARLOS ROBERTO GOMES DOS SANTOS',
  '328': 'MARCELO ROBERTO SILVA',
  '329': 'CARLOS HENRIQUE MARTINS CHAMARELLI',
  '330': 'LUISMAR LIMA DA CONCEICAO',
  '331': 'WANDERSON GOMES DO NASCIMENTO',
  '332': 'AILTON SILVA BORGES',
  '333': 'FABIO ALVES DE SOUSA',
  '334': 'CLEBSON DE OLIVEIRA SANTOS',
  '335': 'JOAO CARLOS DA SILVA FILHO',
  '336': 'ALEXANDRE OLIVEIRA SILVA',
  '337': 'MARLOS ANGELO DA SILVA',
  '338': 'SEM MOTORISTA',
  '339': 'ORMINO WANDERLEY DA SILVA SOUZA',
  '340': 'WILMAR ROBERTO SOUZA',
  '341': 'SIDINALDO HILARIO DE SOUZA',
  '342': 'EDVAN PEREIRA DE SOUZA',
  '343': 'FERNANDO SOUSA DA SILVA',
  '344': 'WELLINGTON JOSE SOARES',
  '345': 'ISADORA APARECIDA COSTA',
  '346': 'WESLEY LUIZ MIRANDA',
  '347': 'FABIO RIBEIRO MARCAL',
  '348': 'ZELENES COSTA SILVA',
  '349': 'REGIMAR JESUS DE SOUSA',
  '350': 'HENRIQUE CARVALHO ALVES',
  '2001': 'JOSE ROBERTO PEREIRA',
  '1011': 'ALMIR DE MELO',
  '1012': 'RONIVALDO DA SILVA GUIMARAES',
  '1013': 'DENIS GONCALVES ARAUJO',
  '1014': 'FABIO ALMEIDA DOS SANTOS',
  '1015': 'ALEXSANDRA CORREIA DOS SANTOS SILVA',
  '1016': 'LEONI LUCENA DE ALMEIDA',
  '1017': 'ALIX TELES GONCALVES',
  '1018': 'JOSIEL DA SILVA LIMA',
  '1019': 'FRANCISCO GILVANDRO DA SILVA',
  '1020': 'RAFAEL SOUSA DE OLIVEIRA',
  '1021': 'FLAUZE ANDRE DA SILVA JUNIOR',
  '1023': 'ALEX LUCINDO OLIVEIRA',
  '1025': 'FERNANDO LUCINDO DE OLIVEIRA',
  '1031': 'ISAIAS RODRIGO SANTOS SILVA',
  '1032': 'HAMILTON ALVES DA SILVA',
  '1033': 'TULIANO CLEANN GOMES DA SILVA',
  '1034': 'JOAO PAULO FERREIRA FRANCISCO',
  '1035': 'ALEXSANDRO SOUZA DE JESUS',
  '1036': 'ODAYLSON OLIVEIRA PEDROSA',
  '1037': 'WAGNER LUCAS FRAGA',
  '1038': 'JERONIMO MOURA OLIVEIRA',
  '1039': 'VICENTE DE PAULA FERREIRA DA SILVA',
  '1040': 'IAGO ANTONIO LOPES',
  '1041': 'LUIS ENRIQUE CONTRERAS',
  '1042': 'FABIO CRISTIANO ALVES DE MIRANDA',
  '1044': 'ANDERSON DE FREITAS PONTE',
  '1045': 'JUAN CARLOS SAAVEDRA VIRLA'
};

// Função para extrair número da frota do nome do veículo
export function extractFleetNumber(nomeVeiculo) {
  if (!nomeVeiculo) return '';
  const match = nomeVeiculo.match(/^(\d+)/);
  return match ? match[1] : nomeVeiculo;
}

// Função para obter o motorista pelo número da frota
export function getDriverName(nomeVeiculo) {
  const fleetNumber = extractFleetNumber(nomeVeiculo);
  return DRIVER_MAP[fleetNumber] || '—';
}

// Função para obter o gestor pelo número da frota
export function getManagerName(nomeVeiculo) {
  const fleetNumber = parseInt(extractFleetNumber(nomeVeiculo), 10);
  if (isNaN(fleetNumber)) return '—';

  // Saulo: 204-225, 1011-1020, 251-255
  if ((fleetNumber >= 204 && fleetNumber <= 225) ||
      (fleetNumber >= 1011 && fleetNumber <= 1020) ||
      (fleetNumber >= 251 && fleetNumber <= 255)) {
    return 'Saulo';
  }

  // Elinete: 226-250
  if (fleetNumber >= 226 && fleetNumber <= 250) {
    return 'Elinete';
  }

  // Reginaldo: 126-150
  if (fleetNumber >= 126 && fleetNumber <= 150) {
    return 'Reginaldo';
  }

  // Jackson: 101-125
  if (fleetNumber >= 101 && fleetNumber <= 125) {
    return 'Jackson';
  }

  // Maickel: 304-326
  if (fleetNumber >= 304 && fleetNumber <= 326) {
    return 'Maickel';
  }

  // Sérgio: 327-350 e 2001
  if ((fleetNumber >= 327 && fleetNumber <= 350) || fleetNumber === 2001) {
    return 'Sérgio';
  }

  // Júnior: 26-50
  if (fleetNumber >= 26 && fleetNumber <= 50) {
    return 'Júnior';
  }

  // Michel: 1021-1050
  if (fleetNumber >= 1021 && fleetNumber <= 1050) {
    return 'Michel';
  }

  return '—';
}